name: Augury
options:
  bundleIdPrefix: xyz.andypants
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.0"
targets:
  Augury:
    type: application
    platform: iOS
    sources:
      - Augury
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: xyz.andypants.augury
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Augury
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
  AuguryTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - AuguryTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: xyz.andypants.augury.tests
    dependencies:
      - target: Augury
